services:
  - type: worker
    name: trader-journal-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.bot
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
